version: "3.11"

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    container_name: lang-backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    container_name: lang-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
