FROM python:3.11-slim

WORKDIR /src

COPY . .

RUN pip install streamlit==1.43.2
RUN pip install requests==2.32.3
RUN pip install python-dotenv==1.0.1


EXPOSE 8080

CMD ["streamlit", "run", "src/run_streamlit.py"]
